// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdbRemoteDirExists(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdbRemoteDirExists'](arg1, arg2, arg3);
}

export function DownloadBeatmap(arg1) {
  return window['go']['main']['App']['DownloadBeatmap'](arg1);
}

export function EventLog(arg1) {
  return window['go']['main']['App']['EventLog'](arg1);
}

export function FetchAllPages(arg1) {
  return window['go']['main']['App']['FetchAllPages'](arg1);
}

export function FetchPage(arg1) {
  return window['go']['main']['App']['FetchPage'](arg1);
}

export function GetAdbPath() {
  return window['go']['main']['App']['GetAdbPath']();
}

export function GetAdbVersion(arg1) {
  return window['go']['main']['App']['GetAdbVersion'](arg1);
}

export function GetDeviceProperties(arg1, arg2) {
  return window['go']['main']['App']['GetDeviceProperties'](arg1, arg2);
}

export function GetDeviceSerial(arg1, arg2) {
  return window['go']['main']['App']['GetDeviceSerial'](arg1, arg2);
}

export function GetDeviceSynthFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetDeviceSynthFiles'](arg1, arg2, arg3);
}

export function GetQuestDeviceModel() {
  return window['go']['main']['App']['GetQuestDeviceModel']();
}

export function GetSynthFilesCount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSynthFilesCount'](arg1, arg2, arg3);
}

export function GetSynthridersFolder() {
  return window['go']['main']['App']['GetSynthridersFolder']();
}

export function InstallAdbWindows() {
  return window['go']['main']['App']['InstallAdbWindows']();
}

export function IsQuestUsbConnected() {
  return window['go']['main']['App']['IsQuestUsbConnected']();
}

export function PushBeatmap(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PushBeatmap'](arg1, arg2, arg3, arg4);
}

export function StartAdbServer(arg1) {
  return window['go']['main']['App']['StartAdbServer'](arg1);
}

export function SyncNewBeatmaps(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SyncNewBeatmaps'](arg1, arg2, arg3, arg4);
}
