// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AdbRemoteDirExists(arg1:string,arg2:string,arg3:string):Promise<boolean>;

export function DownloadBeatmap(arg1:main.Beatmap):Promise<string>;

export function EventLog(arg1:string):Promise<void>;

export function FetchAllPages(arg1:number):Promise<Array<main.BeatmapPage>>;

export function FetchPage(arg1:number):Promise<main.BeatmapPage>;

export function GetAdbPath():Promise<string>;

export function GetAdbVersion(arg1:string):Promise<string>;

export function GetDeviceSerial(arg1:string,arg2:string):Promise<string>;

export function GetDeviceSynthFiles(arg1:string,arg2:string,arg3:string):Promise<Record<string, boolean>>;

export function GetQuestDeviceModel():Promise<string>;

export function GetSynthridersFolder():Promise<string>;

export function IsQuestUsbConnected():Promise<boolean>;

export function PushBeatmap(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartAdbServer(arg1:string):Promise<void>;

export function SyncNewBeatmaps(arg1:Array<main.BeatmapPage>,arg2:Record<string, boolean>,arg3:string,arg4:string):Promise<void>;
